### ISSUE TITLE
how to edit ? 

### ISSUE THREAD

**Issue by samy14** [rob-white/vue-slimgrid#3]
Hi,

I try to active editing of cells in the component but I don't understand how to active that ?  do you have an example ? 

Thank you 
S.

**Comment by rob-white** [comment]
Sorry I'm just now getting to this. Started a new job and haven't had any time to work on open source stuff.

Looks like there was a bug not allowing the grid to go into "editable" mode, but it should be fixed in **0.1.39**

Also added an example to the README documentation.
